### ISSUE TITLE
Unused pad near antenna is GND

### ISSUE THREAD

**Issue by pamribeirox** [bazjo/RS41_Hardware#9]
After some experiments with external antennas and.VNA I've found the unused pad near the antenna connects with the mid ground plane of thr pcb in the.mid layer thu some vias.
It can by onserved with the pcb in front of some light
Soldering a SMA connector between the two pads and being careful not to touch the nearby leds results in optimum adaptation near with a good SWR deep i(low) in the band of operation 400-410 according to my nanoVNA
Thanks for all the info collected and shared!
Regards!

**Comment by bazjo** [comment]
Thank you so much for catching this, already fixed locally and will be fixed by @TjarkG soon.
